services:
  db:
    image: 'mysql:latest'
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_USER: myuser
    ports:
      - '3306:3306'
    volumes:
      - ./config/mysql/database.sql:/docker-entrypoint-initdb.d/database.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - "8082:80"